In [1]:
import pandas as pd
import numpy as np

In [2]:
X = np.array([[1.0],[-3.1],[-7.2], [2.1]])

In [3]:
#converting the input in matrix form
X = X.T
print("Input in matrix form:\n", X)

Input in matrix form:
 [[ 1.  -3.1 -7.2  2.1]]


In [4]:
#assign weights
w = np.array([[2.1], [1.2], [0.3], [1.3]])
w

array([[2.1],
       [1.2],
       [0.3],
       [1.3]])

In [5]:
#add bias
b = -3

In [14]:
def linear_function(x, Derivative=False):
    if not Derivative:
        # Return the partial derivation of the activation function
        return x
    else:
        # Return the activation signal 
        return 1.0

In [11]:
#updating weight
def make_prediction(X, w, b):

    weighted_sum = np.dot(X, w) + b
    first_output = linear_function(weighted_sum)
    return first_output

In [12]:
prediction = make_prediction(X, w, b)

In [13]:
 print(f"The prediction result is: {prediction}")

The prediction result is: [[-4.05]]


In [16]:
def relu(x, Derivative=False):
    if not Derivative:
        return np.maximum(0,x)
    else:
        out = np.ones(x.shape)
        out[(x < 0)]=0
        return out


In [17]:
#updating weight
def make_pred(X, w, b):

    weighted_sum = np.dot(X, w) + b
    out_1 = relu(weighted_sum)
    return out_1

In [18]:
out_1 = make_pred(X, w, b)

In [19]:
print(f"The prediction result is: {out_1}")

The prediction result is: [[0.]]


In [20]:
def linear_function2(x, Derivative=False):
    if not Derivative:
        # Return the partial derivation of the activation function
        return x
    else:
        # Return the activation signal 
        return 1.0

In [21]:
#assign weights
w2 = np.array([[0.1], [1.2], [4.9], [3.1]])
w2

array([[0.1],
       [1.2],
       [4.9],
       [3.1]])

In [34]:
#add bias
b2 = -5

In [57]:
#updating weight
def make_prediction1(X, w2, b2):

    weighted_sum = np.dot(X, w2) + b2
    first_output = linear_function2(weighted_sum)
    return first_output

In [58]:
prediction = make_prediction1(X, w2, b2)

In [59]:
out_2 = make_prediction1(X, w2, b2)

In [60]:
print(f"The prediction result is: {out_2}")

The prediction result is: [[-37.39]]


In [61]:
out_21 = make_pred(X, w2, b2)

In [62]:
print(f"The prediction result is: {out_21}")

The prediction result is: [[0.]]


In [31]:
#assign weights
w3 = np.array([[0.4], [2.6], [2.5], [3.8]])
w3

array([[0.4],
       [2.6],
       [2.5],
       [3.8]])

In [32]:
#add bias
b3 = -8

In [33]:
def linear_function3(x, Derivative=False):
    if not Derivative:
        # Return the partial derivation of the activation function
        return x
    else:
        # Return the activation signal 
        return 1.0

In [63]:
#updating weight
def make_prediction2(X, w3, b3):

    weighted_sum = np.dot(X, w3) + b3
    first_output7 = linear_function3(weighted_sum)
    return first_output7

In [64]:
out_7 = make_prediction2(X, w3, b3)

In [65]:
print(f"The prediction result is: {out_7}")

The prediction result is: [[-25.68]]


In [66]:
out_212 = make_pred(X, w3, b3)

In [67]:
print(f"The prediction result is: {out_212}")

The prediction result is: [[0.]]


4

In [78]:
w6 = [1.1, -4.1, 0.7]
b6 = 5.1
X6 = np.array([[0],[0],[0]])

In [79]:
#converting the input in matrix form
X6 = X6.T
print("Input in matrix form:\n", X)

Input in matrix form:
 [array([[0.]]), array([[0.]]), array([[0.]])]


In [80]:
def linear_function4(x, Derivative=False):
    if not Derivative:
        # Return the partial derivation of the activation function
        return x
    else:
        # Return the activation signal 
        return 1.0

In [81]:
#updating weight
def make_prediction6(X6, w6, b6):

    weighted_sum = np.dot(X6, w6) + b6
    first_output6 = linear_function4(weighted_sum)
    return first_output6

In [82]:
prediction7 = make_prediction6(X6, w6, b6)

In [83]:
 print(f"The prediction result is: {prediction7}")

The prediction result is: [5.1]


In [84]:
def sig(x):
        return 1/(1 +np.exp(-x))

In [85]:
def der(x):
    return sig(x) * (1-sig(x))

In [86]:
#updating weight
def make_pred1(X6, w6, b6):

    weighted_sum = np.dot(X6, w6) + b6
    out_18 = sig(weighted_sum)
    return out_18

In [87]:
out_18 = make_pred1(X6, w6, b6)

In [88]:
print(f"The prediction result is: {out_18}")

The prediction result is: [0.9939402]
